//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdSongLogix.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BirdSongLogix.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.25
        ///New Forest
        ///C:\Users\Joe Addleton\Desktop
        ///C:\Users\Joe Addleton\Desktop
        ///0.17.2
        ///
        ///Locations
        ///New Forest 50.8571,-1.6318
        ///Dartmoor 50.5719,-3.9207
        ///Loch Lomond 56.1114,-4.6289
        ///.
        /// </summary>
        internal static string AutomaticBirdIDConfig {
            get {
                return ResourceManager.GetString("AutomaticBirdIDConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BirdID_V0_02___Release {
            get {
                object obj = ResourceManager.GetObject("BirdID_V0_02___Release", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BirdNetAnalyser {
            get {
                object obj = ResourceManager.GetObject("BirdNetAnalyser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BOU_British_SpeciesList {
            get {
                object obj = ResourceManager.GetObject("BOU_British_SpeciesList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folderUploadImage {
            get {
                object obj = ResourceManager.GetObject("folderUploadImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capercaillie.Tetrao urogallus.U,
        ///Black Grouse.Lyrurus tetrix.U,
        ///Ptarmigan.Lagopus muta.U,
        ///Red Grouse.Lagopus scotica.U,
        ///Quail.Coturnix coturnix.U,
        ///Golden Pheasant.Chrysolophus pictus.U,
        ///Lady Amherst&apos;s Pheasant.Chrysolophus amherstiae.U,
        ///Brent Goose.Branta bernicla.U,
        ///Dark-bellied Brent Goose.Branta bernicla bernicla.U,
        ///Black Brant.Branta bernicla nigricans.SU,
        ///Grey-bellied Brant.Branta bernicla unnamed.SU,
        ///Pale-bellied Brent Goose.Branta bernicla hrota.U,
        ///Red-breasted Goose.Branta ruficollis.RSU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rare_Species {
            get {
                return ResourceManager.GetString("rare_Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refreshSmall {
            get {
                object obj = ResourceManager.GetObject("refreshSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
